/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PreOrder = IDL.Record({
  'customerName' : IDL.Text,
  'packagingSize' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
  'mangoVariant' : IDL.Text,
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllPreOrders' : IDL.Func([], [IDL.Vec(PreOrder)], ['query']),
  'submitPreOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PreOrder = IDL.Record({
    'customerName' : IDL.Text,
    'packagingSize' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
    'mangoVariant' : IDL.Text,
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllPreOrders' : IDL.Func([], [IDL.Vec(PreOrder)], ['query']),
    'submitPreOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };